background            #181818
foreground            #ebe7da
cursor                #ebe7da
selection_background  #176080
color0                #00010a
color8                #7a7a7d
color1                #ff876d
color9                #ff9780
color2                #c8d479
color10               #cdd886
color3                #ffde90
color11               #ffe5a6
color4                #96a2d5
color12               #abb5dd
color5                #e08094
color13               #fb98ac
color6                #aadbaa
color14               #b8e1b8
color7                #d8d5ca
color15               #ebe7da
selection_foreground  #181818
