# vim:fileencoding=utf-8:foldmethod=marker

font_family JetBrains Mono
font_size 13

# BEGIN_KITTY_THEM
# Base
include current-theme.conf
# END_KITTY_THEME

# Make cursor looks like default bar.
shell_integration no-cursor

# Windows
window_padding_width 2

# Tabs
tab_bar_edge top
tab_title_template  "{index}: {title}"
tab_bar_style powerline
tab_powerline_style slanted

# Opt
confirm_os_window_close 0
macos_option_as_alt yes
